title: Miguel Jover
description: Portfolio
author: "Miguel Jover"

theme: minima

# Social links
github_username: mianjoto
linkedin_username: mianjoto

# Header links
header_pages:
  - /index.md
  - /resume.md
  - /projects.md

include:
  - _pages

exclude:
  - README.md 
